AntEnv_v3:
    joints: 8
    input_size: 2
    latent_size: 60
    encoder_layer_sizes: [24, 32, 48]
    decoder_layer_sizes: [48, 32, 24]
    task_layer_sizes: [60, 30, 1]
#    task_layer_sizes: [1,1]
    condition_size: 1
    samples: 100
    perturbation_strength: 0.2
    epochs: 500
