AntEnv_v3:
    joints: 8
    input_size: 2
    latent_size: 2
    encoder_layer_sizes: [12,8,4]
    decoder_layer_sizes: [4,8,12]
    task_layer_sizes: [2,1]
#    task_layer_sizes: [1,1]
    condition_size: 1
    samples: 100
    perturbation_strength: 0.2
    epochs: 100
