AntEnv_v3:
    joints: 8
    input_size: 2
    latent_size: 5
    encoder_layer_sizes: [16,12,8,8]
    decoder_layer_sizes: [8,8,12,16]
    task_layer_sizes: [5,5,5,5,5,5,1,1]
#    task_layer_sizes: [1,1]
    condition_size: 1
    samples: 1000
    perturbation_strength: 1
    epochs: 1000
