AntEnv_v3:
    joints: 8
    input_size: 3
    latent_size: 3
    encoder_layer_sizes: [18, 12, 6]
    decoder_layer_sizes: [6, 12, 18]
    task_layer_sizes: [3, 1]
#    task_layer_sizes: [1,1]
    condition_size: 1
    samples: 100
    perturbation_strength: 0.1
    epochs: 500
