AntEnv_v3:
    joints: 8
    input_size: 3
    latent_size: 4
    encoder_layer_sizes: [18, 12, 8]
    decoder_layer_sizes: [8, 12, 18]
    task_layer_sizes: [4,3,2,1]
    condition_size: 1
    samples: 100
    perturbation_strength: 0.2
    