AntEnv_v3:
    input_size: 4
    latent_size: 6
    encoder_layer_sizes: [25, 18, 12]
    decoder_layer_sizes: [12, 18, 25]
    task_layer_sizes: [6, 4, 1]
    condition_size: 1
    samples: 100
    perturbation_strength: 1
    