default:
    method: "maxdiff"
    max_steps: 1000
    max_frames: 1000000
    model_lr: !!float 3e-4
    reward_scale: 1.0
    model_iter: 5
    model_layers: [200,200]
    model_activation_fun: 'ReLU'
    reward_layers: [200,200]
    reward_activation_fun: 'ReLU'
    name_mod: ''
    weights: None
    batch_size: 256
    planner:
        horizon: 5
        samples: 20
        lam: 0.1
        eps: 0.5
        alpha: 5
        explr_dim: None
        weights: None
        window: False

AntEnv_v3:
    input_size: 32
    latent_size: 5
    encoder_layer_sizes: [10,5]
    decoder_layer_sizes: [5,10]
    model_layers: [512,512,512]
    reward_layers: [512,512,512]
    done_layers: None
    batch_size: 256
    name_mod: '_H20_alpha5'
    planner:
        explr_dim: [0, 1, 2]
        weights: [1.0, 1.0, 0.005]
        horizon: 20
        alpha: 5
        lam: 0.5
        samples: 1000
        window: False
    task_info:
        include_contacts: False
        task: 'orig'
        desired_speed: None